apiVersion: v1
kind: ConfigMap
metadata:
  name: pig-config
  namespace: {{ .Release.Namespace }}
data:
  pig_port: "{{ .Values.service.port }}"
  rabbitmq_adress: {{ .Values.rabbitmq.rabbitmq_adress }}