apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka.name }}
  namespace: {{ .Values.kafka.namespace }}
spec:
  kafka:
    replicas: {{ .Values.kafka.replicas }}
    listeners:
      - name: plain
        port: 8092
        type: internal
        tls: false
      - name: tls
        port: 8093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: {{ .Values.kafka.replicas }}
      transaction.state.log.replication.factor: {{ .Values.kafka.replicas }}
      transaction.state.log.min.isr: 1
    storage:
      type: {{ .Values.kafka.storage.type }}
      size: {{ .Values.kafka.storage.size }}
      class: {{ .Values.kafka.storage.class }}
  zookeeper:
    replicas: {{ .Values.zookeeper.replicas }}
    storage:
      type: {{ .Values.zookeeper.storage.type }}
      size: {{ .Values.zookeeper.storage.size }}
      class: {{ .Values.zookeeper.storage.class }}
  entityOperator:
    topicOperator: {}
    userOperator: {}