image: golang:1.23.7-bookworm

stages:
  - build
  - test
  - deploy

build_binary:
  stage: build
  script:
    - go build

build_docker:
  image: docker
  stage: build
  before_script:
    - env
  services:
    - name: docker:dind
  script:
    - docker build -t goapp2 .

unit_test:
  stage: test
  script:
    - go test ./...

deploy:
  image: debian:stable
  stage: deploy
  before_script:
    - env
    - apt update
    - apt install -y python3 python3-pip openssh-client
    - pip install --break-system-packages ansible
    - mkdir -p ~/.ssh
    - echo "$id_rsa" > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh
    - chmod 600 ~/.ssh/id_rsas
  script:
    - ansible-playbook -i inventory.ini deploy.yaml
    

  