image: golang:1.23.7-bookworm

stages:
  - build
  - test

build_binary:
  stage: build
  script:
    - go build

build_docker:
  image: docker:26.1.3
  stage: build
  services:
    - name: docker:26.1.3-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375/
  before_script:
    - env
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  script:
    - docker build . -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}

unit_test:
  stage: test
  script:
    - go test ./...
