image: golang:1.23.7-bookworm

stages:
  - build
  - test

build_binary:
  stage: build
  script:
    - go build

build_docker:
  image: docker:26.1.3
  stage: build
  before_script:
    - env
  services:
    - name: docker:26.1.3-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $CI_REGISTRY/group/project/image:latest .
    - docker push $CI_REGISTRY/group/project/image:latest

unit_test:
  stage: test
  script:
    - go test ./...
