image: golang:1.23.7-bookworm

stages:
  - build
  - test

build_docker:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker build -t pig:0.0.2

build_binary:
  stage: build
  script:
    - go build

unit_test:
  stage: test
  script:
    - go test ./...