image: golang:1.23.7-bookworm

stages:
  - build
  - test

build_docker:
  stage: build
  image: docker
  before_script:
    - export
    - docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
  services:
    - docker:dind
  script:
    - docker build . -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}

build_binary:
  stage: build
  script:
    - go build

unit_test:
  stage: test
  script:
    - go test ./...