image: it-camp.innoca.local:5005/student103/project-1/golang-build:latest

stages:
  - build
  - test
  - deploy
  - deploy_k8s

build_binary:
  stage: build
  script:
    - go build -o pig .
  artifacts:
    paths:
      - pig

build_docker:
  image: docker:latest
  stage: build
  services:
    - name: it-camp.innoca.local:5005/student103/project-1/docker-dind:latest
  script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .

    - echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
    - docker tag $CI_REGISTRY_IMAGE blur1ng/docker-dind:latest
#    - docker push $DOCKER_USERNAME/docker-dind:latest


#unit_test:
#  stage: test
#  script:
#    - go test ./...
#
#deploy:
#  image: debian:stable
#  stage: deploy
#  before_script:
#    - apt update
#    - apt install -y python3 python3-pip openssh-client
#    - pip install --break-system-packages ansible
#    - mkdir -p ~/.ssh
#    - echo "$id_rsa" > ~/.ssh/id_rsa
#    - chmod 700 ~/.ssh
#    - chmod 600 ~/.ssh/id_rsa
#  script:
#    - ansible-playbook -i inventory.ini deploy.yaml

deploy_k8s:
  stage: deploy_k8s
  image: 
    name: debian:bullseye-slim
    entrypoint: [""]
  before_script:
    - mkdir -p ~/.kube
    - echo $KUBECONFIG > ~/.kube/config
    - apt-get update && apt-get install -y curl

    - curl https://get.helm.sh/helm-v3.17.0-linux-amd64.tar.gz -o helm.tar.gz
    - tar -zxvf helm.tar.gz
    - mv linux-amd64/helm /usr/local/bin/helm

#    - apt-get install -y kubectl
#    - curl -LO "https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl"
#    - mv ./kubectl /usr/local/bin/kubectl

  script:
#    - kubectl apply -f k8s-manifests/base/configmap.yaml
#    - kubectl apply -f k8s-manifests/base/deployment.yaml
#    - kubectl apply -f k8s-manifests/base/service.yaml
#    - kubectl apply -f k8s-manifests/base/ingress.yaml
    - helm upgrade --install pig-helm ./k8s-manifests/pig-helm -f ./k8s-manifests/pig-helm/values.yaml -f ./k8s-manifests/pig-helm/rabbitmq-value.yaml -f ./k8s-manifests/pig-helm/kafka-value.yaml -f ./k8s-manifests/pig-helm/postgres-value.yaml

