image: golang:1.23.7-bookworm

stages:
  - build
  - test

build_binary:
  stage: build
  script:
    - go build

build_docker:
  image: docker
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
  before scripts:
    - docker info

unit_test:
  stage: test
  script:
    - go test ./...