image: golang:1.23.7-bookworm

stages:
  - build
  - test

build_binary:
  stage: build
  script:
    - go build

build_docker:
  image: docker
  stage: build
  before_script:
    - export
    - echo "$PASSWORD" | docker login -u ${GITLAB_USER_LOGIN} --password-stdin
  services:
    - docker:dind
  script:
    - docker build . -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

    

unit_test:
  stage: test
  script:
    - go test ./...
