image: golang:1.23.7-bookworm

stages:
  - build
  - test

build_binary:
  stage: build
  script:
    - go build

build_docker:
  image: docker
  stage: build
  before_script:
    - env
  services:
    - name: dockerdind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA} .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}

unit_test:
  stage: test
  script:
    - go test ./...


  