---
- hosts: all
  remote_user: student103
  tasks:
  - name: Copy pig binary
    ansible.builtin.copy:
      src: pig
      dest: /home/student103/pig
      owner: student103
      group: it-camp-gitlab-users
      mode: "0700"
