apiVersion: apps/v1
kind: Deployment
metadata:
  name: pig
  namespace: eb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pig
  template:
    metadata:
      labels:
        app: pig
    spec:
      containers:
      - name: pig
        image: blur1ng/goapp2
        ports:
        - containerPort: 8000
        env:
        - name: pig_port
          valueFrom:
            configMapKeyRef:
              name: pig-config
              key: pig_port

