apiVersion: apps/v1
kind: Deployment
metadata:
  name: pig
  namespace: eb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pig
  template:
    metadata:
      labels:
        app: pig
    spec:
      containers:
      - name: pig
        image: $DOCKER_USERNAME/goapp2
        ports:
        - containerPort: 8000
